// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    // apiKey: 'AIzaSyAKodPwkqSFcn6yyR1kjXdrpR3O9TVcjko',
    // appId: '1:189872052067:android:039a7239613e2d90e3e556',
    // messagingSenderId: '189872052067',
    // projectId: 'imagestorage-168a8',
    // storageBucket: 'imagestorage-168a8.appspot.com',
    apiKey: 'AIzaSyAzZ4yzikQ8kEC_fKqBmZhbE2W8-YjkT_k',
    appId: '1:505795639238:android:10f443ea2012ebc5b3a4c7',
    messagingSenderId: '505795639238',
    projectId: 'chat-ad85f',
    databaseURL: 'https://chat-ad85f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-ad85f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyb1fkOJIX9NBiH5m0-fj6OSUnAIODPM',
    appId: '1:189872052067:ios:c48eba45cd5e6040e3e556',
    messagingSenderId: '189872052067',
    projectId: 'imagestorage-168a8',
    storageBucket: 'imagestorage-168a8.appspot.com',
    iosClientId: '189872052067-7h5f3anb3tfuksdoqsvb71m7atusqru2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pieceOfCake',
  );
}
